[package]
name = "robby-fischer"
version = "0.1.0"
edition = "2021"

[dependencies]
burktelefon = { path = "burktelefon" }

[workspace]
members = [
    "arm",
    "burktelefon",
    "eagle",
    "parrot",
    "planner",
    "duckchess",
]

[profile.dev]
opt-level = 1
