[package]
name = "planner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
crossterm = "0.26.1"
nalgebra = "0.32.2"
nix = {version = "0.26.2", features = ["term"] }
tui = "0.19.0"
robby-fischer = {path = ".." }
arrayvec = "0.7.2"
lazy_static = "1.4.0"
