[package]
name = "eagle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
freenectrs = "0.1.0"
glam = "0.24.2"
minifb = "0.24.0"
opencv = { version="0.85.3", features=["aruco", "aruco_detector", "xobjdetect", "objdetect", "calib3d"]}
rerun = "0.7.0"
